on: push
  #- branch: main
    

jobs: 
  first-job: 
   # runs-on: windows-latest
    runs-on: ubuntu-latest
    container: node:17.6.0
    steps: 
       # - run: dotnet --version
        - run: node --version
        - run: npm --version

