name: Node Continuous Integration
on: push
  #- branch: main


jobs: 
  first-job:
    name: Build Node
   # runs-on: windows-latest
    runs-on: ubuntu-latest
    container: node:17.6.0
    steps: 
       # - run: dotnet --version
        - run: node --version
        - run: npm --version
        - uses: actions/checkout@v4
        - run: dir

